export const IPC_CHANNELS = {
  BOOKS: {
    GET_ALL: 'books:getAll',
    GET_BY_ID: 'books:getById',
    CREATE: 'books:create',
    UPDATE: 'books:update',
    DELETE: 'books:delete',
    UPDATE_PROGRESS: 'books:updateProgress',
    SEARCH: 'books:search',
  },
  HIGHLIGHTS: {
    GET_BY_BOOK: 'highlights:getByBook',
    GET_BY_ID: 'highlights:getById',
    CREATE: 'highlights:create',
    UPDATE: 'highlights:update',
    DELETE: 'highlights:delete',
    GET_ALL: 'highlights:getAll',
    SEARCH: 'highlights:search',
  },
  CARDS: {
    GET_BY_HIGHLIGHT: 'cards:getByHighlight',
    GET_BY_ID: 'cards:getById',
    CREATE: 'cards:create',
    CREATE_BATCH: 'cards:createBatch',
    CREATE_FOR_EXISTING: 'cards:createForExisting',
    UPDATE: 'cards:update',
    UPDATE_APPLICATION_TAG: 'cards:updateApplicationTag',
    UPDATE_MASTERY_LEVEL: 'cards:updateMasteryLevel',
    DELETE: 'cards:delete',
    GET_DUE: 'cards:getDue',
    GET_BY_BOOK: 'cards:getByBook',
    GET_STATS: 'cards:getStats',
  },
  REVIEWS: {
    CREATE: 'reviews:create',
    GET_BY_CARD: 'reviews:getByCard',
    GET_RECENT: 'reviews:getRecent',
  },
  SUMMARIES: {
    GET_BY_BOOK: 'summaries:getByBook',
    CREATE: 'summaries:create',
    DELETE: 'summaries:delete',
  },
  DAILY_STATS: {
    GET_TODAY: 'dailyStats:getToday',
    GET_RANGE: 'dailyStats:getRange',
    INCREMENT_BOOKS: 'dailyStats:incrementBooks',
    INCREMENT_HIGHLIGHTS: 'dailyStats:incrementHighlights',
    INCREMENT_CARDS: 'dailyStats:incrementCards',
    ADD_READING_TIME: 'dailyStats:addReadingTime',
  },
  WEREAD: {
    SET_API_KEY: 'weread:setApiKey',
    GET_BOOKSHELF: 'weread:getBookshelf',
    FETCH_BOOKMARKS: 'weread:fetchBookmarks',
    FETCH_NOTES: 'weread:fetchNotes',
    FETCH_ALL_CONTENT: 'weread:fetchAllContent',
    FETCH_ALL_CONTENT_BATCH: 'weread:fetchAllContentBatch',
    FETCH_RECOMMENDATIONS: 'weread:fetchRecommendations',
    TEST: 'weread:test',
  },
  READING_DATA: {
    FETCH: 'readingData:fetch',
    FETCH_WEEKLY: 'readingData:fetchWeekly',
    FETCH_MONTHLY: 'readingData:fetchMonthly',
    FETCH_ANNUALLY: 'readingData:fetchAnnually',
    FETCH_OVERALL: 'readingData:fetchOverall',
  },
  AI: {
    SET_CONFIG: 'ai:setConfig',
    GENERATE_CARDS: 'ai:generateCards',
    GENERATE_SUMMARY: 'ai:generateSummary',
    CHAT: 'ai:chat',
    EXPLAIN: 'ai:explain',
    TEST: 'ai:test',
  },
  CONVERSATIONS: {
    CREATE: 'conversations:create',
    GET_ALL: 'conversations:getAll',
    GET_BY_ID: 'conversations:getById',
    UPDATE: 'conversations:update',
    DELETE: 'conversations:delete',
    ADD_MESSAGE: 'conversations:addMessage',
    GET_MESSAGES: 'conversations:getMessages',
    SEARCH: 'conversations:search',
  },
  AGENT: {
    CHAT: 'agent:chat',
    STREAM_CHAT: 'agent:streamChat',
    STREAM_CHAT_WITH_CONTEXT: 'agent:streamChatWithContext',
    CANCEL_STREAM: 'agent:cancelStream',
  },
  // 流式事件 channel（主进程 -> 渲染进程，由主进程 send 触发）
  STREAM: {
    CHUNK: 'ai:streamChunk',
    COMPLETE: 'ai:streamComplete',
    ERROR: 'ai:streamError',
  },
  ADMIN: {
    GET_STATS: 'admin:getStats',
    GET_AGENT_CONFIG: 'admin:getAgentConfig',
    SAVE_AGENT_CONFIG: 'admin:saveAgentConfig',
    RESET_AGENT_CONFIG: 'admin:resetAgentConfig',
    GET_BOOKS_WITH_COUNTS: 'admin:getBooksWithCounts',
    GET_HIGHLIGHTS_BY_BOOK: 'admin:getHighlightsByBook',
    GET_CARDS_BY_BOOK: 'admin:getCardsByBook',
    GET_SESSIONS: 'admin:getSessions',
    GET_SESSION_MESSAGES: 'admin:getSessionMessages',
    GET_PROMPTS: 'admin:getPrompts',
    GET_PROMPT: 'admin:getPrompt',
    SAVE_PROMPT: 'admin:savePrompt',
    RESET_PROMPT: 'admin:resetPrompt',
    RESET_ALL_PROMPTS: 'admin:resetAllPrompts',
    EXPORT_PROMPTS: 'admin:exportPrompts',
    IMPORT_PROMPTS: 'admin:importPrompts',
    GET_DATABASE_SCHEMA: 'admin:getDatabaseSchema',
    GET_TABLE_DATA: 'admin:getTableData',
    CREATE_CUSTOM_PROMPT: 'admin:createCustomPrompt',
    UPDATE_CUSTOM_PROMPT: 'admin:updateCustomPrompt',
    DELETE_CUSTOM_PROMPT: 'admin:deleteCustomPrompt',
    GET_CUSTOM_PROMPTS: 'admin:getCustomPrompts',
  },
  SETTINGS: {
    GET: 'settings:get',
    SET: 'settings:set',
    GET_ALL: 'settings:getAll',
  },
  TOKEN_USAGE: {
    GET_RECENT: 'tokenUsage:getRecent',
    GET_BY_DATE_RANGE: 'tokenUsage:getByDateRange',
    GET_STATS_BY_PROVIDER: 'tokenUsage:getStatsByProvider',
    GET_STATS_BY_FEATURE: 'tokenUsage:getStatsByFeature',
    GET_DAILY_STATS: 'tokenUsage:getDailyStats',
    GET_TOTAL_STATS: 'tokenUsage:getTotalStats',
    CLEAR_ALL: 'tokenUsage:clearAll',
  },
  METHODOLOGIES: {
    GET_ALL: 'methodologies:getAll',
    GET_BY_ID: 'methodologies:getById',
    GET_BY_BOOK: 'methodologies:getByBook',
    CREATE: 'methodologies:create',
    UPDATE: 'methodologies:update',
    DELETE: 'methodologies:delete',
    SEARCH: 'methodologies:search',
    EXTRACT: 'methodologies:extract',
  },
  KNOWLEDGE_CARDS: {
    GET_ALL: 'knowledgeCards:getAll',
    GET_BY_ID: 'knowledgeCards:getById',
    GET_BY_BOOK: 'knowledgeCards:getByBook',
    GET_BY_TYPE: 'knowledgeCards:getByType',
    CREATE: 'knowledgeCards:create',
    UPDATE: 'knowledgeCards:update',
    DELETE: 'knowledgeCards:delete',
    SEARCH: 'knowledgeCards:search',
    DISTILL: 'knowledgeCards:distill',
    CANCEL_DISTILL: 'knowledgeCards:cancelDistill',
    IS_DISTILLING: 'knowledgeCards:isDistilling',
    // 知识卡片蒸馏进度事件（主进程 -> 渲染进程）
    DISTILL_PROGRESS: 'knowledgeCard:distillProgress',
    GENERATE_INTERPRETATION: 'knowledgeCards:generateInterpretation',
    GENERATE_APPLICATION: 'knowledgeCards:generateApplication',
  },
  BOOK_ARCHITECTURE: {
    GET_BY_BOOK: 'bookArchitecture:getByBook',
    CREATE: 'bookArchitecture:create',
    UPDATE: 'bookArchitecture:update',
    DELETE: 'bookArchitecture:delete',
    ANALYZE: 'bookArchitecture:analyze',
  },
  ARTICLES: {
    GET_ALL: 'articles:getAll',
    GET_BY_ID: 'articles:getById',
    GET_UNREAD: 'articles:getUnread',
    GET_FAVORITES: 'articles:getFavorites',
    CREATE: 'articles:create',
    MARK_AS_READ: 'articles:markAsRead',
    TOGGLE_FAVORITE: 'articles:toggleFavorite',
    DELETE: 'articles:delete',
    GET_STATS: 'articles:getStats',
    FETCH_RSS: 'articles:fetchRss',
    TRANSLATE: 'articles:translate',
  },
  VOCABULARY: {
    GET_ALL: 'vocabulary:getAll',
    GET_BY_ID: 'vocabulary:getById',
    GET_BY_WORD: 'vocabulary:getByWord',
    GET_UNMASTERED: 'vocabulary:getUnmastered',
    GET_DUE_FOR_REVIEW: 'vocabulary:getDueForReview',
    CREATE: 'vocabulary:create',
    CREATE_FROM_LOOKUP: 'vocabulary:createFromLookup',
    MARK_AS_MASTERED: 'vocabulary:markAsMastered',
    INCREMENT_REVIEW: 'vocabulary:incrementReview',
    UPDATE_REVIEW_DATA: 'vocabulary:updateReviewData',
    DELETE: 'vocabulary:delete',
    GET_STATS: 'vocabulary:getStats',
    SEARCH: 'vocabulary:search',
  },
  DICTIONARY: {
    LOOKUP: 'dictionary:lookup',
    LOOKUP_BATCH: 'dictionary:lookupBatch',
    GET_SIZE: 'dictionary:getSize',
  },
  SYSTEM: {
    FORCE_SAVE_DATABASE: 'system:forceSaveDatabase',
    CLEAR_CACHE: 'system:clearCache',
    OPEN_EXTERNAL: 'system:openExternal',
    CLEAR_HISTORY: 'system:clearHistory',
    RESET_DATABASE: 'system:resetDatabase',
  },
  FSRS: {
    SET_PARAMETERS: 'fsrs:setParameters',
    RESET_PARAMETERS: 'fsrs:resetParameters',
    GET_PARAMETERS: 'fsrs:getParameters',
    GET_FORECAST: 'fsrs:getForecast',
    GET_OPTIMAL_REVIEW_ORDER: 'fsrs:getOptimalReviewOrder',
    PREVIEW_REVIEW_RATINGS: 'fsrs:previewReviewRatings',
  },
  SKILL: {
    GENERATE: 'skill:generate',
    EXPORT_BATCH: 'skill:exportBatch',
  },
} as const;
